version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Berlin"
    assignees:
      - "okafke"
    reviewers:
      - "okafke"
    commit-message:
      prefix: "gradle"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Berlin"
    assignees:
      - "okafke"
    reviewers:
      - "okafke"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    groups:
      actions-deps:
        patterns:
          - "*"
